dist: trusty
sudo: false
language: node_js
node_js: node
before_script:
  - npm install -g gulp-cli bower
after_install:
  - bower install
script:
  - gulp build:prod

before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Travis"
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  repo: MindongLab/foochow-idioms-web
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: master