version: '2'

services:
  foochow-idioms-api:
    image: foochow-idioms-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports: 
      - "5000:80"
    links:
      - db:mongo
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./export:/import
